### ISSUE TITLE
java.util.ConcurrentModificationException crash

### ISSUE THREAD

**Issue by Thewhitelight** [xiaojinzi123/KComponent#14]
你好 在线上出现了这个异常。改为ConcurrentHashMap应该就没问题了
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1603)
at java.util.HashMap$EntryIterator.next(HashMap.java:1636)
at java.util.HashMap$EntryIterator.next(HashMap.java:1634)
at com.xiaojinzi.component.impl.interceptor.InterceptorCenter.check(Unknown Source:26)
at com.xiaojinzi.component.Component.check(Unknown Source:21)
at com.xiaojinzi.component.impl.application.ModuleManager.doNotifyModuleChanged(Unknown Source:43)
at com.xiaojinzi.component.impl.application.ModuleManager.notifyModuleChanged$lambda$3(Unknown Source:14)
at com.xiaojinzi.component.impl.application.ModuleManager.a(Unknown Source:0)
at com.xiaojinzi.component.impl.application.b.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by xiaojinzi123** [comment]
线上请关闭 debug 模式
